// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6S_GqkVajRAAO86_4_SQTXuzi62fjPao',
    appId: '1:845540435946:web:65192ced3e35acc67a3493',
    messagingSenderId: '845540435946',
    projectId: 't2024it5-campuseventscalendar',
    authDomain: 't2024it5-campuseventscalendar.firebaseapp.com',
    storageBucket: 't2024it5-campuseventscalendar.appspot.com',
    measurementId: 'G-24CMYG0R6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPU6FxzsMvCDhjijQ0LBris6Sm4NFpGsg',
    appId: '1:845540435946:android:29e13e8ef4a4aec17a3493',
    messagingSenderId: '845540435946',
    projectId: 't2024it5-campuseventscalendar',
    storageBucket: 't2024it5-campuseventscalendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9v7Ptrw5u7P5_DA6YAerKABfzvq60g-8',
    appId: '1:845540435946:ios:23d52cf4274b64a77a3493',
    messagingSenderId: '845540435946',
    projectId: 't2024it5-campuseventscalendar',
    storageBucket: 't2024it5-campuseventscalendar.appspot.com',
    iosClientId: '845540435946-8dhjiv1r9251e4ccrkb7860g33gcfena.apps.googleusercontent.com',
    iosBundleId: 'com.example.t2024it5CampuseventscalendarWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9v7Ptrw5u7P5_DA6YAerKABfzvq60g-8',
    appId: '1:845540435946:ios:23d52cf4274b64a77a3493',
    messagingSenderId: '845540435946',
    projectId: 't2024it5-campuseventscalendar',
    storageBucket: 't2024it5-campuseventscalendar.appspot.com',
    iosClientId: '845540435946-8dhjiv1r9251e4ccrkb7860g33gcfena.apps.googleusercontent.com',
    iosBundleId: 'com.example.t2024it5CampuseventscalendarWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6S_GqkVajRAAO86_4_SQTXuzi62fjPao',
    appId: '1:845540435946:web:5b4c790101c80f617a3493',
    messagingSenderId: '845540435946',
    projectId: 't2024it5-campuseventscalendar',
    authDomain: 't2024it5-campuseventscalendar.firebaseapp.com',
    storageBucket: 't2024it5-campuseventscalendar.appspot.com',
    measurementId: 'G-RQ1K6VV29N',
  );
}